import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True
    dependencies = [("users", "0002_role_and_phone"), migrations.swappable_dependency(settings.AUTH_USER_MODEL)]
    operations = [
        migrations.CreateModel(name="Company", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=160, verbose_name="razón social")), ("slug", models.SlugField(unique=True)), ("is_active", models.BooleanField(default=True)), ("primary_color", models.CharField(default="#2563EB", max_length=7)), ("secondary_color", models.CharField(default="#0F172A", max_length=7)), ("accent_color", models.CharField(default="#16A36A", max_length=7)), ("logo_url", models.URLField(blank=True)), ("created_at", models.DateTimeField(auto_now_add=True))], options={"verbose_name_plural": "empresas"}),
        migrations.CreateModel(name="Membership", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("is_active", models.BooleanField(default=True)), ("created_at", models.DateTimeField(auto_now_add=True)), ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to="operations.company")), ("role", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="memberships", to="users.role")), ("supervisor", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="reports", to="operations.membership")), ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="memberships", to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="TruckType", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=80)), ("height_cm", models.PositiveIntegerField()), ("width_cm", models.PositiveIntegerField()), ("length_cm", models.PositiveIntegerField()), ("gross_weight_kg", models.PositiveIntegerField()), ("axle_count", models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(2), django.core.validators.MaxValueValidator(12)])), ("trailer_count", models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(3)])), ("is_active", models.BooleanField(default=True)), ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="truck_types", to="operations.company"))]),
        migrations.CreateModel(name="RestrictedZoneGroup", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=100)), ("description", models.CharField(blank=True, max_length=250)), ("color", models.CharField(default="#DC2626", max_length=7)), ("is_visible", models.BooleanField(default=True)), ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="zone_groups", to="operations.company")), ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_zone_groups", to=settings.AUTH_USER_MODEL))]),
        migrations.CreateModel(name="RestrictedZone", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=120)), ("polygon", models.JSONField(help_text="GeoJSON Polygon en coordenadas longitud/latitud")), ("created_at", models.DateTimeField(auto_now_add=True)), ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="created_zones", to=settings.AUTH_USER_MODEL)), ("group", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="zones", to="operations.restrictedzonegroup"))]),
        migrations.CreateModel(name="PlannedRoute", fields=[("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")), ("name", models.CharField(max_length=140)), ("origin", models.JSONField(help_text="Punto GeoJSON")), ("destination", models.JSONField(help_text="Punto GeoJSON")), ("route_geometry", models.JSONField(blank=True, default=dict)), ("cargo_type", models.CharField(max_length=100)), ("cargo_weight_kg", models.PositiveIntegerField()), ("departure_at", models.DateTimeField()), ("status", models.CharField(choices=[("draft", "Borrador"), ("assigned", "Asignada"), ("in_progress", "En curso"), ("completed", "Completada")], default="draft", max_length=20)), ("distance_m", models.PositiveIntegerField(blank=True, null=True)), ("duration_seconds", models.PositiveIntegerField(blank=True, null=True)), ("here_request", models.JSONField(blank=True, default=dict)), ("created_at", models.DateTimeField(auto_now_add=True)), ("updated_at", models.DateTimeField(auto_now=True)), ("company", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="routes", to="operations.company")), ("driver", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="assigned_routes", to=settings.AUTH_USER_MODEL)), ("planner", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="planned_routes", to=settings.AUTH_USER_MODEL)), ("restricted_zones", models.ManyToManyField(blank=True, related_name="routes", to="operations.restrictedzone")), ("truck_type", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="routes", to="operations.trucktype"))]),
        migrations.AddConstraint(model_name="membership", constraint=models.UniqueConstraint(fields=("company", "user"), name="unique_company_user")),
        migrations.AddIndex(model_name="membership", index=models.Index(fields=["company", "role"], name="membership_company_role_idx")),
        migrations.AddConstraint(model_name="trucktype", constraint=models.UniqueConstraint(fields=("company", "name"), name="unique_company_truck_type")),
        migrations.AddConstraint(model_name="restrictedzonegroup", constraint=models.UniqueConstraint(fields=("company", "name"), name="unique_company_zone_group")),
        migrations.AddIndex(model_name="plannedroute", index=models.Index(fields=["company", "status", "departure_at"], name="route_company_status_idx")),
    ]
